Repository shooterstech/BabelFish, pull requests merged in 2023-05, with the labels that each got.

#44 Decomposed the UserAuthentication constructor to use a InitalizeAsync…
  BabelFish.Tests/AttributeValue/GetAttributeValueTests.cs
  BabelFish.Tests/AttributeValue/SetAttributeValueTests.cs
  BabelFish.Tests/AttributeValue/SetMultiplePhoneNumbersTest.cs
  BabelFish.Tests/Authentication/AuthenticationTests.cs
  BabelFish.Tests/Clubs/ClubsTests.cs
  BabelFish/APIClients/APIClient.cs
  BabelFish/Runtime/Authentication/AuthenticationException.cs
  BabelFish/Runtime/Authentication/UserAuthentication.cs
Labels: bug, enhancement, rezults

#45 Task EST Login
  BabelFish.Tests/AthenaLogin/LoginTest.cs
  BabelFish.Tests/AttributeValue/GetAttributeValueTests.cs
  BabelFish.Tests/AttributeValue/SetAttributeValueTests.cs
  BabelFish.Tests/AttributeValue/SetMultiplePhoneNumbersTest.cs
  BabelFish.Tests/Authentication/AuthenticationTests.cs
  BabelFish.Tests/Clubs/ClubsTests.cs
  BabelFish/APIClients/APIClient.cs
  BabelFish/APIClients/AthenaLoginAPIClient.cs
  BabelFish/BabelFish.csproj
  BabelFish/DataModel/AthenaLogin/ESTUnitActiveSessions.cs
  BabelFish/DataModel/AthenaLogin/ESTUnitLogin.cs
  BabelFish/DataModel/AthenaLogin/ESTUnitLoginSession.cs
  BabelFish/DataModel/AthenaLogin/ESTUnitLoginUser.cs
  BabelFish/DataModel/AthenaLogin/ESTUnitLogout.cs
  BabelFish/DataModel/OrionMatch/ResultEvent.cs
  BabelFish/DataModel/OrionMatch/ResultList.cs
  BabelFish/Requests/AthenaLogin/AthenaEmployLoginCodeAuthenticatedRequest.cs
  BabelFish/Requests/AthenaLogin/AthenaListActiveSessionsAuthenticatedRequest.cs
  BabelFish/Requests/AthenaLogin/AthenaLogoutSessionAuthenticatedRequest.cs
  BabelFish/Requests/OrionMatchAPI/GetResultListPublicRequest.cs
  BabelFish/Responses/AthenaLogin/AthenaEmployLoginCodeAuthenticatedResponse.cs
  BabelFish/Responses/AthenaLogin/AthenaListActiveSessionsAuthenticatedResponse.cs
  BabelFish/Responses/AthenaLogin/AthenaLogoutSessionAuthenticatedResponse.cs
  BabelFish/Responses/AthenaLogin/ESTUnitActiveSessionsWrapper.cs
  BabelFish/Responses/AthenaLogin/ESTUnitLoginWrapper.cs
  BabelFish/Responses/AthenaLogin/ESTUnitLogoutWrapper.cs
  BabelFish/Runtime/Authentication/AuthenticationException.cs
  BabelFish/Runtime/Authentication/UserAuthentication.cs
Labels: enhancement, est

#47 Updated score history entry to include MatchName and MatchLocation
  BabelFish/DataModel/ScoreHistory/ScoreHistoryEntry.cs
Labels: enhancement, orion
